[build]
builder = "NIXPACKS"
buildCommand = "pip install -e ."

[deploy]
startCommand = "bash -c './run_datasette.sh'"
preDeployCommand = "bash -c 'chmod +x run_scraper.sh && (./run_scraper.sh || true)'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[volumes.data]
mountPath = "./data"

# Scraper service configuration
[services.scraper]
[services.scraper.build]
builder = "NIXPACKS"
buildCommand = "pip install -e ."

[services.scraper.deploy]
startCommand = "bash -c 'chmod +x run_scraper.sh && ./run_scraper.sh'"
cronSchedule = "0 0 30 * *"
