[build]
builder = "NIXPACKS"
buildCommand = "pip install -e ."

[deploy]
startCommand = "bash -c './run_datasette.sh'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[volumes.data]
mountPath = "./data"
